DROP TABLE IF EXISTS KINGJAMES

CREATE TABLE KINGJAMES (freq INT, word STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' STORED AS TEXTFILE

SHOW TABLES

DESCRIBE KINGJAMES

LOAD DATA INPATH "/user/cloudera/bible_freq" INTO TABLE KINGJAMES

SELECT * FROM KINGJAMES WHERE freq > 6000 SORT BY freq DESC LIMIT 20

SELECT COUNT(*) FROM KINGJAMES WHERE lower(word) like 'w%' AND length(word) >= 4 AND freq > 250